DROP TABLE "TEJASNETWORKS_ME_ROM 2";
CREATE TABLE "TEJASNETWORKS_ME_ROM 2"
(
    pk                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key with sequence auto-generation
    native_ems_name    VARCHAR2(255),      -- Native EMS (assumed string)
    me_name            VARCHAR2(255) CONSTRAINT rom2_unique_me_name UNIQUE,      -- Managed Element name
    user_label         VARCHAR2(255),      -- User label
    product_name       VARCHAR2(255),      -- Product name
    ip_address         VARCHAR2(255),      -- IP Address
    software_version   VARCHAR2(255),      -- Software Version
    location           VARCHAR2(255),      -- Location
    communication_state           NUMBER(1,0),      -- Communication State
    circle             VARCHAR2(255) DEFAULT 'ROM',      -- Circle
    vendor             VARCHAR2(50) DEFAULT 'TEJAS',
    last_modified_date TIMESTAMP,          -- Last modified date, using timestamp for timezone support
    is_deleted         NUMBER(1,0) DEFAULT 0,
    delta_timestamp  TIMESTAMP WITH TIME ZONE
);

CREATE INDEX "idx_TEJAS_ME_ROM2_native_ems_name" ON "TEJASNETWORKS_ME_ROM 2"(native_ems_name);

ALTER TABLE "TEJASNETWORKS_ME_ROM 2" add (
    delta_timestamp timestamp with time zone
);

ALTER TABLE "TEJASNETWORKS_ME_ROM 2" add (
    communication_state           NUMBER(1,0)
);

CREATE TABLE "TEJASNETWORKS_ME_ROM 2_TEMP" AS SELECT * FROM "TEJASNETWORKS_ME_ROM 2" WHERE 1=0;