DROP TABLE ECI_ME_KA;
CREATE TABLE ECI_ME_KA
(
    pk                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key with sequence auto-generation
    native_ems_name    VARCHAR2(255),      -- Native EMS (assumed string)
    me_name            VARCHAR2(255) CONSTRAINT ka_unique_me_name UNIQUE,      -- Managed Element name
    user_label         VARCHAR2(255),      -- User label
    product_name       VARCHAR2(255),      -- Product name
    ip_address         VARCHAR2(255),      -- IP Address
    software_version   VARCHAR2(255),      -- Software Version
    location           VARCHAR2(255),      -- Location
    communication_state           NUMBER(1,0),      -- Communication State
    circle             VARCHAR2(255) DEFAULT 'KA',      -- Circle
    vendor             VARCHAR2(50) DEFAULT 'ECI',
    last_modified_date TIMESTAMP,          -- Last modified date, using timestamp for timezone support
    is_deleted         NUMBER(1,0) DEFAULT 0,
    delta_timestamp  TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_ECI_ME_KA_native_ems_name ON ECI_ME_KA(native_ems_name);

ALTER TABLE ECI_ME_KA add (
    delta_timestamp timestamp with time zone
);

ALTER TABLE ECI_ME_KA add (
    communication_state           NUMBER(1,0)
);


CREATE TABLE ECI_ME_KA_TEMP AS SELECT * FROM ECI_ME_KA WHERE 1=0;
