DROP TABLE "TEJASNETWORKS_TOPOLOGY_MUM 2";
CREATE TABLE "TEJASNETWORKS_TOPOLOGY_MUM 2"
(
    pk                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key with sequence auto-generation
    tp_link_name       VARCHAR2(400) CONSTRAINT mum1_unique_tp_link_name UNIQUE,
    native_ems_name    VARCHAR2(400),
    rate               NUMBER,
    link_type          VARCHAR2(50),
    direction          VARCHAR2(50),
    a_end_ems          VARCHAR2(100),
    a_end_vendor       VARCHAR2(10) DEFAULT 'TEJAS',
    z_end_vendor       VARCHAR2(10) DEFAULT 'TEJAS',
    a_end_me_name      VARCHAR2(100),
    a_end_me_label     VARCHAR2(100),
    a_end_port_name    VARCHAR2(150),
    a_end_port_label   VARCHAR2(100),
    z_end_ems          VARCHAR2(100),
    z_end_me_name      VARCHAR2(100),
    z_end_me_label     VARCHAR2(100),
    z_end_port_name    VARCHAR2(150),
    z_end_port_label   VARCHAR2(100),
    user_label         VARCHAR2(400),
    protection         VARCHAR2(50),
    ring_name          VARCHAR2(300),
    inconsistent       VARCHAR2(50),
    technology_layer   VARCHAR2(50),
    topology_type      VARCHAR2(10),
    circle             VARCHAR2(50) DEFAULT 'MUM',
    vendor             VARCHAR2(50) DEFAULT 'TEJAS',
    last_modified_date TIMESTAMP WITH TIME ZONE,
    is_deleted         NUMBER(1,0) DEFAULT 0,
    delta_timestamp  TIMESTAMP WITH TIME ZONE
);

-- Indexes for faster SELECT queries
CREATE INDEX idx_TEJASNETWORKS_TOPOLOGY_MUM2_native_ems_name ON "TEJASNETWORKS_TOPOLOGY_MUM 2" (native_ems_name);
CREATE INDEX idx_TEJASNETWORKS_TOPOLOGY_MUM2_topology_type ON "TEJASNETWORKS_TOPOLOGY_MUM 2" (topology_type);