DROP TABLE ECI_TOPOLOGY_GJ;
CREATE TABLE ECI_TOPOLOGY_GJ
(
    pk                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key with sequence auto-generation
    tp_link_name       VARCHAR2(400) CONSTRAINT gj_unique_tp_link_name UNIQUE,
    native_ems_name    VARCHAR2(400),
    rate               NUMBER,
    link_type          VARCHAR2(50),
    direction          VARCHAR2(50),
    a_end_ems          VARCHAR2(100),
    a_end_me_name      VARCHAR2(100),
    a_end_me_label     VARCHAR2(100),
    a_end_port_name    VARCHAR2(100),
    a_end_port_label   VARCHAR2(100),
    z_end_ems          VARCHAR2(100),
    z_end_me_name      VARCHAR2(100),
    z_end_me_label     VARCHAR2(100),
    z_end_port_name    VARCHAR2(100),
    z_end_port_label   VARCHAR2(100),
    user_label         VARCHAR2(400),
    protection         VARCHAR2(50),
    ring_name          VARCHAR2(300),
    inconsistent       VARCHAR2(50),
    technology_layer   VARCHAR2(50),
    topology_type      VARCHAR2(10),
    circle             VARCHAR2(50) DEFAULT 'GJ',
    vendor             VARCHAR2(50) DEFAULT 'ECI',
    last_modified_date TIMESTAMP WITH TIME ZONE,
    is_deleted         NUMBER(1,0) DEFAULT 0
);

-- Indexes for faster SELECT queries
CREATE INDEX idx_ECI_TOPOLOGY_GJ_native_ems_name ON ECI_TOPOLOGY_GJ (native_ems_name);
CREATE INDEX idx_ECI_TOPOLOGY_GJ_topology_type ON ECI_TOPOLOGY_GJ (topology_type);