DROP TABLE "TEJASNETWORKS_PTP_MUM 1";
CREATE TABLE "TEJASNETWORKS_PTP_MUM 1"
(
    pk                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key with sequence auto-generation
    ptp_id             VARCHAR2(255),
    port_location      VARCHAR2(255),
    circle             VARCHAR2(50) DEFAULT 'MUM',
    vendor             VARCHAR2(50) DEFAULT 'TEJAS',
    me_name            VARCHAR2(255),
    me_label           VARCHAR2(255),
    product_name       VARCHAR2(255),
    trace_tx           VARCHAR2(255),
    trace_rx           VARCHAR2(255),
    port_native_name   VARCHAR2(255),
    slot               VARCHAR2(255),
    rate               VARCHAR2(50),
    type               VARCHAR2(50),
    is_deleted         NUMBER(1,0) DEFAULT 0,
    last_modified_date TIMESTAMP,
    delta_timestamp  TIMESTAMP WITH TIME ZONE
);

CREATE INDEX "idx_TEJASNETWORKS_PTP_MUM 1_me_name" ON "TEJASNETWORKS_PTP_MUM 1"(me_name);
CREATE INDEX "idx_TEJASNETWORKS_PTP_MUM 1_me_label" ON "TEJASNETWORKS_PTP_MUM 1"(me_label);
CREATE INDEX "idx_TEJASNETWORKS_PTP_MUM 1_port_native_name" ON "TEJASNETWORKS_PTP_MUM 1"(port_native_name);
CREATE INDEX "idx_TEJASNETWORKS_PTP_MUM 1_port_location" ON "TEJASNETWORKS_PTP_MUM 1"(port_location);
