DROP TABLE "TEJASNETWORKS_SNC_MUM 1";


CREATE TABLE "TEJASNETWORKS_SNC_MUM 1"
(
    pk                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key with sequence auto-generation
    snc_id             VARCHAR2(255),
    snc_name           VARCHAR2(1000),
    circuit_id         NUMBER,                                              -- Integer for circuit_id
    srf_id             NUMBER,                                              -- Integer for srf_id
    snc_rate           VARCHAR2(255),
    v_cat              VARCHAR2(255),
    a_end_me           VARCHAR2(255),
    a_end_me_label     VARCHAR2(255),
    a_end_ptp          VARCHAR2(255),
    a_end_ptp_label    VARCHAR2(255),
    a_end_channel      VARCHAR2(255),
    z_end_me           VARCHAR2(255),
    z_end_me_label     VARCHAR2(255),
    z_end_ptp          VARCHAR2(255),
    z_end_ptp_label    VARCHAR2(255),
    z_end_channel      VARCHAR2(255),
    circle             VARCHAR2(50) DEFAULT 'MUM1',
    vendor             VARCHAR2(50) DEFAULT 'TEJAS',
    is_deleted         NUMBER(1,0) DEFAULT 0,
    last_modified_date TIMESTAMP WITH TIME ZONE,
    delta_timestamp  TIMESTAMP WITH TIME ZONE
);

CREATE INDEX "idx_TEJASNETWORKS_SNC_MUM 1_snc_id" ON "TEJASNETWORKS_SNC_MUM 1" (snc_id);
CREATE INDEX "idx_TEJASNETWORKS_SNC_MUM 1_snc_name" ON "TEJASNETWORKS_SNC_MUM 1" (snc_name);
CREATE INDEX "idx_TEJASNETWORKS_SNC_MUM 1_circuit_id" ON "TEJASNETWORKS_SNC_MUM 1" (circuit_id);
CREATE INDEX "idx_TEJASNETWORKS_SNC_MUM 1_srf_id" ON "TEJASNETWORKS_SNC_MUM 1" (srf_id);
