DROP TABLE IMPORT_JOB;

-- Table for Import Jobs
CREATE TABLE import_job
(
    job_id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_timestamp      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    end_timestamp        TIMESTAMP,
    duration             VARCHAR(100),
    vendor               VARCHAR(20)                         NOT NULL,
    circle               VARCHAR(10)                         NOT NULL,
    job_state            VARCHAR2(20) CHECK (job_state IN ('NEW', 'STARTED', 'RUNNING', 'CANCELLED', 'FAILED', 'FINISHED')) NOT NULL,
    run_by               VARCHAR2(50) NOT NULL,
    discovery_item       VARCHAR2(100), -- Specific to import jobs
    discovery_item_count NUMBER,
    error_details        CLOB
);