DROP TABLE ECI_SDH_TRAIL_TN;

CREATE TABLE ECI_SDH_TRAIL_TN
(
    "TRAIL_ID"           VARCHAR2(255),
    "USER_LABEL"         VARCHAR2(400),
    "CIRCUIT_ID"         VARCHAR2(300),
    "RATE"               VARCHAR2(260),
    "TECHNOLOGY"         VARCHAR2(4000),
    "SPECIFICATION"      VARCHAR2(2600),
    "PATH_TYPE"          VARCHAR2(260),
    "VENDOR"             VARCHAR2(26) DEFAULT 'ECI',
    "TOPOLOGY"           VARCHAR2(4000),
    "A_END_DROP_NODE"    VARCHAR2(2600),
    "Z_END_DROP_NODE"    VARCHAR2(2600),
    "A_END_DROP_PORT"    VARCHAR2(2600),
    "Z_END_DROP_PORT"    VARCHAR2(2600),
    "SEQUENCE"           VARCHAR2(300),
    "CHANNEL"            VARCHAR2(2600),
    "A_END_NODE"         VARCHAR2(2600),
    "Z_END_NODE"         VARCHAR2(2600),
    "A_END_PORT"         VARCHAR2(2600),
    "Z_END_PORT"         VARCHAR2(2600),
    "TOPOLOGY_TYPE"      VARCHAR2(2000),
    "CIRCLE"             VARCHAR2(200) DEFAULT 'TN',
    "SRF_ID"             VARCHAR2(500),
    "LAST_MODIFIED_TIME" TIMESTAMP WITH TIME ZONE
);