CREATE TABLE equipment
(
    pk                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-increment
    me_name             VARCHAR2(255),
    me_label            VARCHAR2(255),
    user_label          VARCHAR2(255),
    software_version    VARCHAR2(50),
    serial_number       VARCHAR2(100),
    expected_equipment  VARCHAR2(255),
    installed_equipment VARCHAR2(255),
    location            VARCHAR2(255),
    is_deleted          CHAR(1) DEFAULT 'N',                                     -- Use 'N' for FALSE, 'Y' for TRUE
    last_modified_date  TIMESTAMP WITH TIME ZONE
);
