CREATE TABLE ECI_SNC_GJ
(
    pk                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key with sequence auto-generation
    snc_id             VARCHAR2(255) NOT NULL,
    snc_name           VARCHAR2(400),
    circuit_id         NUMBER,                                              -- Integer for circuit_id
    srf_id             NUMBER,                                              -- Integer for srf_id
    snc_rate           VARCHAR2(255),
    v_cat              VARCHAR2(255),
    a_end_device_name  VARCHAR2(255),
    a_end_user_label   VARCHAR2(255),
    a_end_ptp          VARCHAR2(255),
    a_end_label        VARCHAR2(255),
    a_end_channel      VARCHAR2(255),
    z_end_device_name  VARCHAR2(255),
    z_end_user_label   VARCHAR2(255),
    z_end_ptp          VARCHAR2(255),
    z_end_label        VARCHAR2(255),
    z_end_channel      VARCHAR2(255),
    circle             VARCHAR2(50) DEFAULT 'GJ',
    vendor             VARCHAR2(50) DEFAULT 'ECI',
    last_modified_date TIMESTAMP
);

CREATE INDEX idx_ECI_SNC_GJ_snc_id ON ECI_SNC_GJ (snc_id);
CREATE INDEX idx_ECI_SNC_GJ_snc_name ON ECI_SNC_GJ (snc_name);
CREATE INDEX idx_ECI_SNC_GJ_circuit_id ON ECI_SNC_GJ (circuit_id);
CREATE INDEX idx_ECI_SNC_GJ_srf_id ON ECI_SNC_GJ (srf_id);

