-- ME --

DROP TABLE ECI_ME_AP;
CREATE TABLE ECI_ME_AP
(
    pk                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key with sequence auto-generation
    native_ems_name    VARCHAR2(255),      -- Native EMS (assumed string)
    me_name            VARCHAR2(255) CONSTRAINT ap_unique_me_name UNIQUE,      -- Managed Element name
    user_label         VARCHAR2(255),      -- User label
    product_name       VARCHAR2(255),      -- Product name
    ip_address         VARCHAR2(255),      -- IP Address
    software_version   VARCHAR2(255),      -- Software Version
    location           VARCHAR2(255),      -- Location
    circle             VARCHAR2(255) DEFAULT 'AP',      -- Circle
    vendor             VARCHAR2(50) DEFAULT 'ECI',
    last_modified_date TIMESTAMP WITH TIME ZONE,          -- Last modified date, using timestamp for timezone support
    is_deleted         NUMBER(1,0) DEFAULT 0
);

CREATE INDEX idx_ECI_ME_AP_native_ems_name ON ECI_ME_AP(native_ems_name);

-- EQ --

DROP TABLE ECI_EQUIPMENT_AP;
CREATE TABLE ECI_EQUIPMENT_AP
(
    pk                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-increment
    me_name             VARCHAR2(255),
    me_label            VARCHAR2(255),
    user_label          VARCHAR2(255),
    software_version    VARCHAR2(50),
    serial_number       VARCHAR2(100),
    expected_equipment  VARCHAR2(255),
    installed_equipment VARCHAR2(255),
    location            VARCHAR2(255),
    circle             VARCHAR2(255) DEFAULT 'AP',      -- Circle
    vendor             VARCHAR2(50) DEFAULT 'ECI',
    is_deleted          NUMBER(1,0) DEFAULT 0,
    last_modified_date  TIMESTAMP WITH TIME ZONE
);

-- PTP --

DROP TABLE ECI_PTP_AP;
CREATE TABLE ECI_PTP_AP
(
    pk                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key with sequence auto-generation
    ptp_id             VARCHAR2(255),
    port_location      VARCHAR2(255),
    circle             VARCHAR2(50) DEFAULT 'AP',
    vendor             VARCHAR2(50) DEFAULT 'ECI',
    me_name            VARCHAR2(255),
    me_label           VARCHAR2(255),
    product_name       VARCHAR2(255),
    trace_tx           VARCHAR2(255),
    trace_rx           VARCHAR2(255),
    port_native_name   VARCHAR2(255),
    slot               VARCHAR2(255),
    rate               VARCHAR2(50),
    type               VARCHAR2(50),
    is_deleted         NUMBER(1,0) DEFAULT 0,
    last_modified_date TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_ECI_PTP_AP_me_name ON ECI_PTP_AP(me_name);
CREATE INDEX idx_ECI_PTP_AP_me_label ON ECI_PTP_AP(me_label);
CREATE INDEX idx_ECI_PTP_AP_port_native_name ON ECI_PTP_AP(port_native_name);
CREATE INDEX idx_ECI_PTP_AP_port_location ON ECI_PTP_AP(port_location);


-- TOPOLOGY --

DROP TABLE ECI_TOPOLOGY_AP;
CREATE TABLE ECI_TOPOLOGY_AP
(
    pk                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key with sequence auto-generation
    tp_link_name       VARCHAR2(400) CONSTRAINT ap_unique_tp_link_name UNIQUE,
    native_ems_name    VARCHAR2(400),
    rate               NUMBER,
    link_type          VARCHAR2(50),
    direction          VARCHAR2(50),
    a_end_ems          VARCHAR2(100),
    a_end_me_name      VARCHAR2(100),
    a_end_me_label     VARCHAR2(100),
    a_end_port_name    VARCHAR2(100),
    a_end_port_label   VARCHAR2(100),
    z_end_ems          VARCHAR2(100),
    z_end_me_name      VARCHAR2(100),
    z_end_me_label     VARCHAR2(100),
    z_end_port_name    VARCHAR2(100),
    z_end_port_label   VARCHAR2(100),
    user_label         VARCHAR2(400),
    protection         VARCHAR2(50),
    ring_name          VARCHAR2(300),
    inconsistent       VARCHAR2(50),
    technology_layer   VARCHAR2(50),
    circle             VARCHAR2(50) DEFAULT 'AP',
    vendor             VARCHAR2(50) DEFAULT 'ECI',
    last_modified_date TIMESTAMP WITH TIME ZONE,
    is_deleted         NUMBER(1,0) DEFAULT 0
);

CREATE INDEX idx_ECI_TOPOLOGY_AP_native_ems_name ON ECI_TOPOLOGY_AP (native_ems_name);

-- SNC --

DROP TABLE ECI_SNC_AP;
CREATE TABLE ECI_SNC_AP
(
    pk                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key with sequence auto-generation
    snc_id             VARCHAR2(255),
    snc_name           VARCHAR2(255),
    circuit_id         NUMBER,                                              -- Integer for circuit_id
    srf_id             NUMBER,                                              -- Integer for srf_id
    snc_rate           VARCHAR2(255),
    v_cat              VARCHAR2(255),
    a_end_me           VARCHAR2(255),
    a_end_me_label     VARCHAR2(255),
    a_end_ptp          VARCHAR2(255),
    a_end_ptp_label    VARCHAR2(255),
    a_end_channel      VARCHAR2(255),
    z_end_me           VARCHAR2(255),
    z_end_me_label   VARCHAR2(255),
    z_end_ptp          VARCHAR2(255),
    z_end_ptp_label        VARCHAR2(255),
    z_end_channel      VARCHAR2(255),
    circle             VARCHAR2(50) DEFAULT 'AP',
    vendor             VARCHAR2(50) DEFAULT 'ECI',
    is_deleted         NUMBER(1,0) DEFAULT 0,
    last_modified_date TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_ECI_SNC_AP_snc_id ON ECI_SNC_AP (snc_id);
CREATE INDEX idx_ECI_SNC_AP_snc_name ON ECI_SNC_AP (snc_name);
CREATE INDEX idx_ECI_SNC_AP_circuit_id ON ECI_SNC_AP (circuit_id);
CREATE INDEX idx_ECI_SNC_AP_srf_id ON ECI_SNC_AP (srf_id);


