DROP TABLE ECI_PTP_ROM;

CREATE TABLE ECI_PTP_ROM
(
    pk                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key with sequence auto-generation
    ptp_id             VARCHAR2(255),
    port_location      VARCHAR2(255),
    circle             VARCHAR2(50) DEFAULT 'ROM',
    vendor             VARCHAR2(50) DEFAULT 'ECI',
    me_name            VARCHAR2(255),
    me_label           VARCHAR2(255),
    product_name       VARCHAR2(255),
    trace_tx           VARCHAR2(255),
    trace_rx           VARCHAR2(255),
    port_native_name   VARCHAR2(255),
    slot               VARCHAR2(255),
    rate               VARCHAR2(50),
    type               VARCHAR2(50),
    is_deleted         NUMBER(1,0) DEFAULT 0,
    last_modified_date TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_ECI_PTP_ROM_me_name ON ECI_PTP_ROM(me_name);
CREATE INDEX idx_ECI_PTP_ROM_me_label ON ECI_PTP_ROM(me_label);
CREATE INDEX idx_ECI_PTP_ROM_port_native_name ON ECI_PTP_ROM(port_native_name);
CREATE INDEX idx_ECI_PTP_ROM_port_location ON ECI_PTP_ROM(port_location);
